// Code generated by MockGen. DO NOT EDIT.
// Source: list_item_service.go

// Package service is a generated GoMock package.
package service

import (
	models "SuperListsAPI/cmd/listItems/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIListItemRepository is a mock of IListItemRepository interface.
type MockIListItemRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIListItemRepositoryMockRecorder
}

// MockIListItemRepositoryMockRecorder is the mock recorder for MockIListItemRepository.
type MockIListItemRepositoryMockRecorder struct {
	mock *MockIListItemRepository
}

// NewMockIListItemRepository creates a new mock instance.
func NewMockIListItemRepository(ctrl *gomock.Controller) *MockIListItemRepository {
	mock := &MockIListItemRepository{ctrl: ctrl}
	mock.recorder = &MockIListItemRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIListItemRepository) EXPECT() *MockIListItemRepositoryMockRecorder {
	return m.recorder
}

// BulkDelete mocks base method.
func (m *MockIListItemRepository) BulkDelete(tasksToDelete []models.ListItem) (*int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkDelete", tasksToDelete)
	ret0, _ := ret[0].(*int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkDelete indicates an expected call of BulkDelete.
func (mr *MockIListItemRepositoryMockRecorder) BulkDelete(tasksToDelete interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkDelete", reflect.TypeOf((*MockIListItemRepository)(nil).BulkDelete), tasksToDelete)
}

// Create mocks base method.
func (m *MockIListItemRepository) Create(item models.ListItem) (*models.ListItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", item)
	ret0, _ := ret[0].(*models.ListItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIListItemRepositoryMockRecorder) Create(item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIListItemRepository)(nil).Create), item)
}

// Delete mocks base method.
func (m *MockIListItemRepository) Delete(listItemID string) (*int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", listItemID)
	ret0, _ := ret[0].(*int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockIListItemRepositoryMockRecorder) Delete(listItemID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIListItemRepository)(nil).Delete), listItemID)
}

// DeleteListItemsByListID mocks base method.
func (m *MockIListItemRepository) DeleteListItemsByListID(listId string) (*int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteListItemsByListID", listId)
	ret0, _ := ret[0].(*int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteListItemsByListID indicates an expected call of DeleteListItemsByListID.
func (mr *MockIListItemRepositoryMockRecorder) DeleteListItemsByListID(listId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteListItemsByListID", reflect.TypeOf((*MockIListItemRepository)(nil).DeleteListItemsByListID), listId)
}

// Get mocks base method.
func (m *MockIListItemRepository) Get(listItemID string) (*models.ListItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", listItemID)
	ret0, _ := ret[0].(*models.ListItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockIListItemRepositoryMockRecorder) Get(listItemID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIListItemRepository)(nil).Get), listItemID)
}

// GetItemsListByListID mocks base method.
func (m *MockIListItemRepository) GetItemsListByListID(listId string) (*[]models.ListItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItemsListByListID", listId)
	ret0, _ := ret[0].(*[]models.ListItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItemsListByListID indicates an expected call of GetItemsListByListID.
func (mr *MockIListItemRepositoryMockRecorder) GetItemsListByListID(listId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItemsListByListID", reflect.TypeOf((*MockIListItemRepository)(nil).GetItemsListByListID), listId)
}

// MarkAsCompleted mocks base method.
func (m *MockIListItemRepository) MarkAsCompleted(tasksToDelete []models.ListItem) (*int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsCompleted", tasksToDelete)
	ret0, _ := ret[0].(*int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkAsCompleted indicates an expected call of MarkAsCompleted.
func (mr *MockIListItemRepositoryMockRecorder) MarkAsCompleted(tasksToDelete interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsCompleted", reflect.TypeOf((*MockIListItemRepository)(nil).MarkAsCompleted), tasksToDelete)
}

// MarkAsPending mocks base method.
func (m *MockIListItemRepository) MarkAsPending(tasksToDelete []models.ListItem) (*int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsPending", tasksToDelete)
	ret0, _ := ret[0].(*int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkAsPending indicates an expected call of MarkAsPending.
func (mr *MockIListItemRepositoryMockRecorder) MarkAsPending(tasksToDelete interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsPending", reflect.TypeOf((*MockIListItemRepository)(nil).MarkAsPending), tasksToDelete)
}

// Update mocks base method.
func (m *MockIListItemRepository) Update(item models.ListItem) (*models.ListItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", item)
	ret0, _ := ret[0].(*models.ListItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockIListItemRepositoryMockRecorder) Update(item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIListItemRepository)(nil).Update), item)
}
