// Code generated by MockGen. DO NOT EDIT.
// Source: lists.go

// Package handler is a generated GoMock package.
package handler

import (
	models "SuperListsAPI/cmd/listItems/models"
	models0 "SuperListsAPI/cmd/lists/models"
	models1 "SuperListsAPI/cmd/userLists/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIListService is a mock of IListService interface.
type MockIListService struct {
	ctrl     *gomock.Controller
	recorder *MockIListServiceMockRecorder
}

// MockIListServiceMockRecorder is the mock recorder for MockIListService.
type MockIListServiceMockRecorder struct {
	mock *MockIListService
}

// NewMockIListService creates a new mock instance.
func NewMockIListService(ctrl *gomock.Controller) *MockIListService {
	mock := &MockIListService{ctrl: ctrl}
	mock.recorder = &MockIListServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIListService) EXPECT() *MockIListServiceMockRecorder {
	return m.recorder
}

// BulkDelete mocks base method.
func (m *MockIListService) BulkDelete(listsToDelete []models0.List) (*int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkDelete", listsToDelete)
	ret0, _ := ret[0].(*int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkDelete indicates an expected call of BulkDelete.
func (mr *MockIListServiceMockRecorder) BulkDelete(listsToDelete interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkDelete", reflect.TypeOf((*MockIListService)(nil).BulkDelete), listsToDelete)
}

// Create mocks base method.
func (m *MockIListService) Create(list models0.List) (*models0.List, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", list)
	ret0, _ := ret[0].(*models0.List)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIListServiceMockRecorder) Create(list interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIListService)(nil).Create), list)
}

// Delete mocks base method.
func (m *MockIListService) Delete(listID string) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", listID)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockIListServiceMockRecorder) Delete(listID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIListService)(nil).Delete), listID)
}

// Get mocks base method.
func (m *MockIListService) Get(listId string) (*models0.List, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", listId)
	ret0, _ := ret[0].(*models0.List)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockIListServiceMockRecorder) Get(listId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIListService)(nil).Get), listId)
}

// GetListByInvitationCode mocks base method.
func (m *MockIListService) GetListByInvitationCode(invitationCode string) (*models0.List, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetListByInvitationCode", invitationCode)
	ret0, _ := ret[0].(*models0.List)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetListByInvitationCode indicates an expected call of GetListByInvitationCode.
func (mr *MockIListServiceMockRecorder) GetListByInvitationCode(invitationCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListByInvitationCode", reflect.TypeOf((*MockIListService)(nil).GetListByInvitationCode), invitationCode)
}

// GetLists mocks base method.
func (m *MockIListService) GetLists(userId string) (*[]models0.List, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLists", userId)
	ret0, _ := ret[0].(*[]models0.List)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLists indicates an expected call of GetLists.
func (mr *MockIListServiceMockRecorder) GetLists(userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLists", reflect.TypeOf((*MockIListService)(nil).GetLists), userId)
}

// Update mocks base method.
func (m *MockIListService) Update(list models0.List) (*models0.List, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", list)
	ret0, _ := ret[0].(*models0.List)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockIListServiceMockRecorder) Update(list interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIListService)(nil).Update), list)
}

// MockIUserListService is a mock of IUserListService interface.
type MockIUserListService struct {
	ctrl     *gomock.Controller
	recorder *MockIUserListServiceMockRecorder
}

// MockIUserListServiceMockRecorder is the mock recorder for MockIUserListService.
type MockIUserListServiceMockRecorder struct {
	mock *MockIUserListService
}

// NewMockIUserListService creates a new mock instance.
func NewMockIUserListService(ctrl *gomock.Controller) *MockIUserListService {
	mock := &MockIUserListService{ctrl: ctrl}
	mock.recorder = &MockIUserListServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUserListService) EXPECT() *MockIUserListServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIUserListService) Create(list models1.UserList) (*models1.UserList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", list)
	ret0, _ := ret[0].(*models1.UserList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIUserListServiceMockRecorder) Create(list interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIUserListService)(nil).Create), list)
}

// Delete mocks base method.
func (m *MockIUserListService) Delete(userListID *[]uint) (*int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", userListID)
	ret0, _ := ret[0].(*int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockIUserListServiceMockRecorder) Delete(userListID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIUserListService)(nil).Delete), userListID)
}

// Get mocks base method.
func (m *MockIUserListService) Get(userListID string) (*models1.UserList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", userListID)
	ret0, _ := ret[0].(*models1.UserList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockIUserListServiceMockRecorder) Get(userListID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIUserListService)(nil).Get), userListID)
}

// GetUserListsByListID mocks base method.
func (m *MockIUserListService) GetUserListsByListID(listID string) (*[]models1.UserList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserListsByListID", listID)
	ret0, _ := ret[0].(*[]models1.UserList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserListsByListID indicates an expected call of GetUserListsByListID.
func (mr *MockIUserListServiceMockRecorder) GetUserListsByListID(listID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserListsByListID", reflect.TypeOf((*MockIUserListService)(nil).GetUserListsByListID), listID)
}

// GetUserListsByUserID mocks base method.
func (m *MockIUserListService) GetUserListsByUserID(userId string) (*[]models1.UserList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserListsByUserID", userId)
	ret0, _ := ret[0].(*[]models1.UserList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserListsByUserID indicates an expected call of GetUserListsByUserID.
func (mr *MockIUserListServiceMockRecorder) GetUserListsByUserID(userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserListsByUserID", reflect.TypeOf((*MockIUserListService)(nil).GetUserListsByUserID), userId)
}

// MockIListItemService is a mock of IListItemService interface.
type MockIListItemService struct {
	ctrl     *gomock.Controller
	recorder *MockIListItemServiceMockRecorder
}

// MockIListItemServiceMockRecorder is the mock recorder for MockIListItemService.
type MockIListItemServiceMockRecorder struct {
	mock *MockIListItemService
}

// NewMockIListItemService creates a new mock instance.
func NewMockIListItemService(ctrl *gomock.Controller) *MockIListItemService {
	mock := &MockIListItemService{ctrl: ctrl}
	mock.recorder = &MockIListItemServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIListItemService) EXPECT() *MockIListItemServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIListItemService) Create(item models.ListItem) (*models.ListItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", item)
	ret0, _ := ret[0].(*models.ListItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIListItemServiceMockRecorder) Create(item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIListItemService)(nil).Create), item)
}

// Delete mocks base method.
func (m *MockIListItemService) Delete(listItemID string) (*int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", listItemID)
	ret0, _ := ret[0].(*int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockIListItemServiceMockRecorder) Delete(listItemID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIListItemService)(nil).Delete), listItemID)
}

// DeleteListItemsByListID mocks base method.
func (m *MockIListItemService) DeleteListItemsByListID(listId string) (*int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteListItemsByListID", listId)
	ret0, _ := ret[0].(*int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteListItemsByListID indicates an expected call of DeleteListItemsByListID.
func (mr *MockIListItemServiceMockRecorder) DeleteListItemsByListID(listId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteListItemsByListID", reflect.TypeOf((*MockIListItemService)(nil).DeleteListItemsByListID), listId)
}

// Get mocks base method.
func (m *MockIListItemService) Get(listItemID string) (*models.ListItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", listItemID)
	ret0, _ := ret[0].(*models.ListItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockIListItemServiceMockRecorder) Get(listItemID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIListItemService)(nil).Get), listItemID)
}

// GetItemsListByListID mocks base method.
func (m *MockIListItemService) GetItemsListByListID(listId string) (*[]models.ListItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItemsListByListID", listId)
	ret0, _ := ret[0].(*[]models.ListItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItemsListByListID indicates an expected call of GetItemsListByListID.
func (mr *MockIListItemServiceMockRecorder) GetItemsListByListID(listId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItemsListByListID", reflect.TypeOf((*MockIListItemService)(nil).GetItemsListByListID), listId)
}

// Update mocks base method.
func (m *MockIListItemService) Update(item models.ListItem) (*models.ListItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", item)
	ret0, _ := ret[0].(*models.ListItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockIListItemServiceMockRecorder) Update(item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIListItemService)(nil).Update), item)
}
