// Code generated by MockGen. DO NOT EDIT.
// Source: lists.go

// Package handler is a generated GoMock package.
package handler

import (
	models "SuperListsAPI/cmd/lists/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIListService is a mock of IListService interface.
type MockIListService struct {
	ctrl     *gomock.Controller
	recorder *MockIListServiceMockRecorder
}

// MockIListServiceMockRecorder is the mock recorder for MockIListService.
type MockIListServiceMockRecorder struct {
	mock *MockIListService
}

// NewMockIListService creates a new mock instance.
func NewMockIListService(ctrl *gomock.Controller) *MockIListService {
	mock := &MockIListService{ctrl: ctrl}
	mock.recorder = &MockIListServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIListService) EXPECT() *MockIListServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIListService) Create(list models.List) (*models.List, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", list)
	ret0, _ := ret[0].(*models.List)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIListServiceMockRecorder) Create(list interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIListService)(nil).Create), list)
}

// Delete mocks base method.
func (m *MockIListService) Delete(listId string) (*int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", listId)
	ret0, _ := ret[0].(*int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockIListServiceMockRecorder) Delete(listId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIListService)(nil).Delete), listId)
}

// Get mocks base method.
func (m *MockIListService) Get(listId string) (*models.List, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", listId)
	ret0, _ := ret[0].(*models.List)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockIListServiceMockRecorder) Get(listId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIListService)(nil).Get), listId)
}

// GetLists mocks base method.
func (m *MockIListService) GetLists(userId string) (*[]models.List, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLists", userId)
	ret0, _ := ret[0].(*[]models.List)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLists indicates an expected call of GetLists.
func (mr *MockIListServiceMockRecorder) GetLists(userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLists", reflect.TypeOf((*MockIListService)(nil).GetLists), userId)
}

// Update mocks base method.
func (m *MockIListService) Update(list models.List) (*models.List, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", list)
	ret0, _ := ret[0].(*models.List)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockIListServiceMockRecorder) Update(list interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIListService)(nil).Update), list)
}
