// Code generated by MockGen. DO NOT EDIT.
// Source: list_service.go

// Package service is a generated GoMock package.
package service

import (
	models "SuperListsAPI/cmd/lists/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIListRepository is a mock of IListRepository interface.
type MockIListRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIListRepositoryMockRecorder
}

// MockIListRepositoryMockRecorder is the mock recorder for MockIListRepository.
type MockIListRepositoryMockRecorder struct {
	mock *MockIListRepository
}

// NewMockIListRepository creates a new mock instance.
func NewMockIListRepository(ctrl *gomock.Controller) *MockIListRepository {
	mock := &MockIListRepository{ctrl: ctrl}
	mock.recorder = &MockIListRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIListRepository) EXPECT() *MockIListRepositoryMockRecorder {
	return m.recorder
}

// BulkDelete mocks base method.
func (m *MockIListRepository) BulkDelete(listsToDelete []models.List) (*int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkDelete", listsToDelete)
	ret0, _ := ret[0].(*int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkDelete indicates an expected call of BulkDelete.
func (mr *MockIListRepositoryMockRecorder) BulkDelete(listsToDelete interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkDelete", reflect.TypeOf((*MockIListRepository)(nil).BulkDelete), listsToDelete)
}

// Create mocks base method.
func (m *MockIListRepository) Create(list models.List) (*models.List, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", list)
	ret0, _ := ret[0].(*models.List)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIListRepositoryMockRecorder) Create(list interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIListRepository)(nil).Create), list)
}

// Delete mocks base method.
func (m *MockIListRepository) Delete(listID string) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", listID)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockIListRepositoryMockRecorder) Delete(listID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIListRepository)(nil).Delete), listID)
}

// Get mocks base method.
func (m *MockIListRepository) Get(listId string) (*models.List, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", listId)
	ret0, _ := ret[0].(*models.List)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockIListRepositoryMockRecorder) Get(listId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIListRepository)(nil).Get), listId)
}

// GetListByInvitationCode mocks base method.
func (m *MockIListRepository) GetListByInvitationCode(invitationCode string) (*models.List, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetListByInvitationCode", invitationCode)
	ret0, _ := ret[0].(*models.List)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetListByInvitationCode indicates an expected call of GetListByInvitationCode.
func (mr *MockIListRepositoryMockRecorder) GetListByInvitationCode(invitationCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListByInvitationCode", reflect.TypeOf((*MockIListRepository)(nil).GetListByInvitationCode), invitationCode)
}

// GetLists mocks base method.
func (m *MockIListRepository) GetLists(userId string) (*[]models.List, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLists", userId)
	ret0, _ := ret[0].(*[]models.List)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLists indicates an expected call of GetLists.
func (mr *MockIListRepositoryMockRecorder) GetLists(userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLists", reflect.TypeOf((*MockIListRepository)(nil).GetLists), userId)
}

// Update mocks base method.
func (m *MockIListRepository) Update(list models.List) (*models.List, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", list)
	ret0, _ := ret[0].(*models.List)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockIListRepositoryMockRecorder) Update(list interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIListRepository)(nil).Update), list)
}
